version: '3.8'

services:
  data-processor:
    build: .
    volumes:
      - .:/code
      - ./geodata:/geodata
    environment:
      DATA_DIR: /geodata
      TOLERANCE: 0.001
      HIGH_TOLERANCE: 0.2
    command: /bin/sh /code/prepare.sh
