{{- if .Values.geocoding.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "geocoding-helm.fullname" . }}-geocoding
  labels:
    app: {{ template "geocoding-helm.fullname" . }}
    component: geocoding
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "geocoding-helm.fullname" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.geocoding.containerPort }}

{{- end }}