version: '3.8'

services:
  geocoding:
    build: .
    ports:
      - "${SERVICE_PORT}:8001"
    volumes:
      - .:/code
      - ./geodata-prep/geodata:/geodata
    environment:
      WAB_FILE_PATH: /geodata/simple.wab.fgb
      GAUL_FILE_PATH: /geodata/simple.gaul.gpkg
    command: /bin/sh -c "uvicorn service:app --host 0.0.0.0 --port 8001 --reload --workers 1"
