version: '3.8'

services:
  geocoding:
    build: .
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    volumes:
      - .:/code
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/sh -c "uvicorn service:app --host 0.0.0.0 --port ${SERVICE_PORT}"
