version: '3.8'

services:
  geocoding:
    build: .
    ports:
      - "${SERVICE_PORT}:8001"
    volumes:
      - .:/code
      - ./geodata:/geodata
    environment:
      DATA_PATH: /geodata
    command: /bin/sh -c "uvicorn service:app --host 0.0.0.0 --port 8001 --workers 1"
