version: '3.8'

services:
  geocoding:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "service:app", "--host", "0.0.0.0", "--port", "8000"]
