version: '3.8'

services:
  geocoding:
    build: .
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    volumes:
      - .:/code
      - data:${GPKG_DIR_BASE_PATH}
    environment:
      GPKG_DIR_BASE_PATH: ${GPKG_DIR_BASE_PATH}
    command: /bin/sh -c "uvicorn service:app --host 0.0.0.0 --port ${SERVICE_PORT} --workers 1"

volumes:
  data:
