environment: test

image:
  name: ghcr.io/ifrcgo/geocoding-service
  tag: random-tag

geocoding:
  enabled: true
  replicaCount: 1
  containerPort: 8002
  resources:
    requests:
      cpu: "200m"
      memory: 5Gi
    limits:
      cpu: "2"
      memory: 6Gi

ingress:
  enabled: true
  host: test.com
  className: "nginx"

sharedVolume:
  persistence:
    storageClassName: "longhorn"
    size: 3Gi