environment: prod

image:
  name: SET-BY-CICD-IMAGE
  tag: SET-BY-CICD-TAG
  PullPolicy: IfNotPresent

geocoding:
  enabled: true
  replicaCount: 1
  containerPort: 8002
  resources:
    requests:
      cpu: "200m"
      memory: 5Gi
    limits:
      cpu: "2"
      memory: 6Gi
  persistence:
    enabled: false
    storageClassName: ""
    size: 3Gi
    accessModes:
      - ReadWriteOnce