environment: production

image:
  name:
  tag:

geocoding:
  enabled: true
  replicaCount: 1
  containerPort: 8002
  resources:
    requests:
      cpu: "200m"
      memory: 5Gi
    limits:
      cpu: "2"
      memory: 6Gi
  persistence:
    enabled: true