image:
  name: SET-BY-CICD-IMAGE
  tag: SET-BY-CICD-TAG
  PullPolicy: IfNotPresent

fullnameOverride: ""
nameOverride: ""

server:
  enabled: true
  serviceName: ""
  fullServiceName: ""
  replicaCount: 1
  containerPort: 8002
  resources:
    requests:
      cpu: "200m"
      memory: 5Gi
    limits:
      cpu: "2"
      memory: 6Gi
  persistence:
    enabled: true
    storageClassName: ""
    size: 3Gi
    accessModes:
      - ReadWriteOnce
