environment: prod

image:
  name: SET-BY-CICD-IMAGE
  tag: SET-BY-CICD-TAG
  PullPolicy: IfNotPresent

geocoding:
  enabled: true
  replicaCount: 1
  containerPort: 8002
  resources:
    requests:
      cpu: "200m"
      memory: 5Gi
    limits:
      cpu: "2"
      memory: 6Gi

ingress:
  enabled: true
  className:
  host: 
  tls:
    enable: false
    secretName: ""

sharedVolume:
  persistence:
    storageClassName: ""
    size: "10G"